# Generated by Django 3.2.8 on 2021-12-09 22:19

from django.conf import settings
from django.db import migrations, models
import feed.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0002_alter_post_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user_name',
            field=models.ForeignKey(on_delete=models.SET(feed.models.get_deleted_user_instance), related_name='details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(feed.models.get_deleted_user_instance), related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
