# Generated by Django 3.2.8 on 2021-12-14 22:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0005_alter_post_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='adult_content',
            field=models.ManyToManyField(blank=True, related_name='adult', to=settings.AUTH_USER_MODEL),
        ),
    ]
