# Generated by Django 3.2.8 on 2021-12-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_post_adult_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='adult_content',
        ),
        migrations.AddField(
            model_name='post',
            name='adult_content',
            field=models.BooleanField(default=True),
        ),
    ]
