# Generated by Django 3.2.8 on 2021-12-15 18:22

from django.conf import settings
from django.db import migrations, models
import feed.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0007_auto_20211214_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=models.SET(feed.models.get_deleted_user_instance), related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
