# Generated by Django 3.2.8 on 2021-12-15 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0008_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='attending',
            field=models.ManyToManyField(blank=True, related_name='attending', to=settings.AUTH_USER_MODEL),
        ),
    ]
