# Generated by Django 3.2.8 on 2021-12-16 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import feed.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0010_alter_events_attending'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_comment', models.CharField(max_length=600)),
                ('event_comment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_events', to='feed.events')),
                ('events_user', models.ForeignKey(on_delete=models.SET(feed.models.get_deleted_user_instance), related_name='comment_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
