# Generated by Django 3.2.8 on 2021-12-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_chat_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
