# Generated by Django 3.2.8 on 2021-12-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_auto_20211219_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='site',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
