# Generated by Django 3.2.8 on 2021-12-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_alter_live_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.URLField(verbose_name=''),
        ),
    ]
